Style(#95): 피드 카드 content 프리뷰 20글자 제한
kakao-tech-campus-2nd-step3/Team15_FE pull request #105
Opened 2024-11-03 15:01 UTC by joshuayeyo

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [X] CSS 변경

### 반영 브랜치
to Team15_FE/Weekly_9
### 작업 내용 및 변경 사항
- content 프리뷰 20글자 제한
### 테스트 결과 이미지(화면 캡쳐해서)
<img width="444" alt="スクリーンショット 0006-11-04 0 01 10" src="https://github.com/user-attachments/assets/3f4a320d-f4ad-446b-af5b-5c955f31a028">

### Todo

### 이슈 링크
#95 
### 리뷰어 멘션하기
@eunjin210

2024-11-03 15:27 UTC, eunjin210 reviewed
혹시 글자들 앞에 공백 생기는거 의도하신걸까요?

2024-11-04 00:16 UTC, joshuayeyo commented
> 혹시 글자들 앞에 공백 생기는거 의도하신걸까요?

제가 글자 정렬에 대해 딱히 제한을 두지 않아서 생긴 일입니다. 방금 우측 정렬로 수정하였습니다.

2024-11-04 01:36 UTC, eunjin210 requested changes
요청했습니다 !

2024-11-04 06:03 UTC, joshuayeyo commented on src/components/feature/feed/post/Card/index.tsx
> +    margin-right: 1rem;
변경하였습니다.
![Uploading スクリーンショット 0006-11-04 15.03.21.png…]()

2024-11-04 13:44 UTC, eunjin210 approved these changes

2024-11-04 13:45 UTC, merged

2024-11-04 13:46 UTC, joshuayeyo commented
20글자가 아니라 150글자로 바꿨었는ㄷ..