Feat(#81) challenge 구현
kakao-tech-campus-2nd-step3/Team15_FE pull request #106
Opened 2024-11-04 13:49 UTC by eunjin210

- 제목 : feat(issue 번호) : 기능명

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치
feat/81/challenge -> Weekly_9

### 작업 내용 및 변경 사항
챌린지 페이지 구현
[x] challenge 작성 모달
[x] challege 아이템 조회

### 테스트 결과 이미지(화면 캡쳐해서)
![image](https://github.com/user-attachments/assets/2f2d65e0-0c62-4669-b54d-e6e9295d3fc5)

#### 챌린지 작성 모달
![image](https://github.com/user-attachments/assets/eb7485c7-eb0e-455d-b429-d0e4ebfa73b5)

### Todo
[ ] 페이지 필터링  
[ ] 챌린지 조회 페이지
[ ] 챌린지 인증글 페이지

### 이슈 링크
#81 
### 리뷰어 멘션하기
@joshuayeyo

2024-11-04 13:58 UTC, joshuayeyo requested changes
수정이 필요한 부분 몇 개 적어뒀습니다!

2024-11-04 13:58 UTC, joshuayeyo commented on src/components/feature/challenge/post/Card/index.tsx
> +  profile: string;
pfp혹은 profilePics로 하면 더 좋을 것 같습니다.
(개인적으로는 pfp를 더 선호)

2024-11-04 13:58 UTC, joshuayeyo commented on src/components/feature/challenge/section/ChallengeForm/index.tsx
커밋 제목에 typo가 있네용

2024-11-04 13:58 UTC, joshuayeyo commented on src/components/feature/images/UploadImage/index.tsx
> +import input_image from '@/assets/imput_image.png';
default로 모두 수정해주세요..!
input_image는 적절치 않은 것 같습니다🤨. (헷갈려요)

2024-11-04 13:58 UTC, joshuayeyo commented on src/assets/imput_image.png
좋은 아이디어네요!
저도 PostFeeds에 사용하도록 하겠습니다😎

2024-11-06 07:30 UTC, eunjin210 commented on src/components/feature/challenge/section/ChallengeForm/index.tsx
변경사항 여러개를 한번에 올리다보니 typo가 좀 있어 새로 올린 pr comment 달아두겠습니다 죄송합니다

2024-11-06 07:35 UTC, eunjin210 commented on src/components/feature/challenge/post/Card/index.tsx
> +  profile: string;
수정해서 pr 올렸습니다

2024-11-06 07:35 UTC, eunjin210 commented on src/components/feature/images/UploadImage/index.tsx
> +import input_image from '@/assets/imput_image.png';
수정해서 올렸습니다 ! 변수명 헷갈리는거 있으면 말씀해주세요 바로 변경하겠습니다 ~

2024-11-06 08:40 UTC, joshuayeyo approved these changes
다 확인 했습니다. 큰 이슈들은 아니라, 다음 PR때 반영하거나 그대로 두셔도 될 것 같아요!
고생하셨습니다. 머지해주세용

2024-11-06 08:40 UTC, joshuayeyo commented on src/components/feature/challegeDetail/Contents/index.tsx
> +  const [userpoint, setuserPoint] = useState<number | null>(null);
setUserPoint로 하면 더 좋을 것 같습니다!
다음 PR때 수정해주시면 좋을 것 같아요

2024-11-06 08:40 UTC, joshuayeyo commented on src/components/feature/challegeDetail/Contents/index.tsx
> +            console.log(res);
다음 PR때는 console.log 최대한 빼고 보내주세용

2024-11-06 08:40 UTC, joshuayeyo commented on src/components/feature/challenge/post/Card/index.tsx
확인했습니다!
변수명 변경은 refactor가 더 좋은 것 같아요.
Style은 CSS나 디자인 변경에만 사용하기로..!

2024-11-06 08:40 UTC, joshuayeyo commented on src/pages/ChallengeDetail/index.tsx
> +        console.log(result);
다른 커밋에 적은 것과 같습니다. console.log는 최대한 빼고 network 탭에서 확인하기로,,!

2024-11-06 08:41 UTC, joshuayeyo commented
conflict는 제가 수정해뒀어용

2024-11-06 09:56 UTC, merged