[Week 10] 10주차 코드 리뷰 요청합니다.
kakao-tech-campus-2nd-step3/Team15_FE pull request #114
Opened 2024-11-08 14:06 UTC by joshuayeyo

## @joshuayeyo
###  
## @eunjin210 
###

2024-11-11 03:53 UTC, minsekim1 commented on src/components/feature/home/Card/index.tsx
> +                    <br/>
<br/> 태그 대신 스타일을 props로 전달하여 <CommonImage /> 컴포넌트나 <CardBody />에서 간격을 제어하는 방식이 더 구조적이고 유지보수하기 좋을거게요.
스타일은 컴포넌트의 외부에서 제어하는 것이 좋기 때문에, props로 간격을 전달하는 방식이 코드 일관성과 재사용성 면에서 유리합니다.

- 예시
```
const CommonCard = ({ maxWidth, imageURL, title, content, profileImage, username }: Props) => {
  return (
    <>
      <Card maxW={maxWidth}>
        {/* <Link></Link> 추가해서 카드 누르면 해당 게시글로 갈 수 있게 */}
        <CardBody>
          <CommonImage 
            src={imageURL} 
            ratio="square"
            style={{ marginBottom: '16px' }} // 이미지 아래 여백 추가
          />
```

2024-11-11 03:56 UTC, minsekim1 commented on src/components/feature/home/Section/Landing-items/index.tsx
> +                username={'반휘혈'}
pstatic.net이나 블로그 이미지들은 해당 게시물이 삭제되거나 변경되었을때 이미지가 바뀔 수 있어요.
이럴때는 다운로드해서 public asset에 넣는게 좋아 보입니다.

(참고 사항)
실제 현업에서는 
`백엔드에 api를 만들어 링크를 보내면 다운로드 -> 이미지 압축(.avif 확장자로 변환) -> AWS S3 (미디어 저장소) 에 저장 -> 이미지 url 반환`
위 처리를 통해서 이미지 CDN에 직접 저장하여 활용합니다.

2024-11-11 03:59 UTC, minsekim1 commented on src/types/index.tsx
`src/types/index.tsx` -> `src/types/index.d.ts`

타입 정의 파일은 .d.ts 확장자를 사용하는 것이 일반적입니다. .d.ts 파일은 TypeScript에서 타입 선언만 포함된 파일임을 명확하게 나타내며, 이렇게 하면 컴파일러가 이 파일을 구현 코드가 아니라 타입 정의로 인식합니다. 따라서, 코드 유지보수성과 가독성이 향상됩니다.

일부 프레임워크나 빌드 도구에서는 .tsx 파일에 React 컴포넌트가 포함되지 않거나 JSX 구문이 없을 경우 에러를 발생시킬 수도 있습니다. 이는 .tsx 파일이 컴포넌트를 내보내는 파일이라는 기대에 맞지 않기 때문입니다. 따라서 타입 정의 파일을 .d.ts로 변경하는 것이 더 안전하고, 파일 용도에 대한 오해를 줄일 수 있습니다.

2024-11-11 04:00 UTC, minsekim1 requested changes
.d.ts에 대한 부분와 pstatic 같은 임시 미디어 저장소같은경우 처리만 하면 될 것 같습니다!

2024-11-13 04:58 UTC, joshuayeyo commented on src/types/index.tsx
https://github.com/kakao-tech-campus-2nd-step3/Team15_FE/pull/133/commits/9651f703d5ffb8b4add74e49bd9942d66bc9146a

반영하였습니다!

2024-11-13 05:01 UTC, joshuayeyo commented on src/components/feature/home/Section/Landing-items/index.tsx
> +                username={'반휘혈'}
https://github.com/kakao-tech-campus-2nd-step3/Team15_FE/pull/140/commits/c690b79429431e7ef25dabff7b396c2abeebeeab

해당 부분은 아직 데이터 map을 구현하지 않은 상태였습니다😥.
어제 구현하여 작성된 게시글들의 cover를 서버에서 받아오는 방식으로 구현하였습니다!

2024-11-17 04:28 UTC, minsekim1 approved these changes

2024-11-17 04:28 UTC, closed without merging