[Week6] 6주차 weekdays 코드 리뷰 요청
kakao-tech-campus-2nd-step3/Team15_FE pull request #69
Opened 2024-10-11 14:26 UTC by joshuayeyo

**지난주차 리뷰해주신 부분들은 현재 반영 중에 있습니다!**

## 정원(@joshuayeyo)

### 1. 상태관리 및 코드작성 관련 질문
글 작성을 구현하려고 하는데, 이미지upload섹션, 글form 섹션은 개별 컴포넌트로 두고 하나의 Post섹션으로 감싸려고 합니다. 
이 경우, useState를 상위 컴포넌트인 Post 섹션에 다 두고 prop을 아래로 내려주는 식으로 작성해보니 코드가 생각보다 많이 길어지고 꼬이는데(200줄이 넘어갑니다..), 조금 더 간결하게 작성할 수 있을 방법이 없을까 고민됩니다..:(

prop이나 각종 유틸 함수들을 관리할 좋은 방법은 역시 새롭게 커스텀 훅 따로 작성해서 import 해서 사용하는 것일까요..?:(

## 은진(@eunjin210)

2024-10-13 02:49 UTC, minsekim1 requested changes

2024-10-13 02:49 UTC, minsekim1 commented on src/api/instance/index.ts
> +const jwtToken = localStorage.getItem('jwt_token');
이렇개 할경우 해당 파일을 읽을때 1회만 jwtToken을 읽고 access token에 넣게 될 거에요. axios create 는 인스턴스를 만들고 나서 이후에는 해더를 변경하지 않아요.

따라서 함수를 추가로 만들어서 axios호출마다 jwt 토큰이 있는지 (로그아웃 시는 삭제 처리) 확인해야합니다.

또는 로그아웃 시에 axios create를 한번 더 수행해도 되지만 axios 호출마다 jwt 토큰을 가져오는 것이 더 적합해 보이네요.

2024-10-13 02:49 UTC, minsekim1 commented on src/components/common/Sidebar/index.tsx
> +  function Sidebar({ isOpen, setIsOpen }: { isOpen: boolean; setIsOpen: any }) {
setIsOpen 에 any 대신 boolean을 set 하는 함수를 넣어주는게 좋아보여요. 이 부분은 gpt에게 물어보면 어떤 type으로 해야할지 알려줄거에요.

2024-10-13 02:49 UTC, minsekim1 commented on src/components/common/layouts/Container/index.tsx
> +    justifyContent?: 'center' | 'flex-start' | 'flex-end' | 'space-between' | 'space-around';
css 속성 전체를 사용할 경우에는 CSSProperties type을 참고하여 넣는것이 좋아요. 물론, 그 중 일부만 수용할 경우 이 처럼 처리해도 문제 없습니다.

2024-10-13 02:49 UTC, minsekim1 commented on src/components/stories/Header.tsx
> +        <svg
svg는 파일로 따로 저장하여 관리하며 코드 가독성이 더욱 좋을 것 같아요.

2024-10-13 02:49 UTC, minsekim1 commented on src/components/stories/assets/avif-test-image.avif
의도한 것일지는 모르겠으나 .avif 확장자로 변환하여 이미지를 관리하는것은 용량면에서 아주 탁월한 선택입니다.

저희 플랫폼에서는 대부분의 jpg jpeg heic png 를 모두 .avif 로 s3에 저장하여 관리합니다.
프론트에서 사용하는 에셋뿐만 아니라 유저가 사진을 업로드해도 백엔드에서 .avif 로 바꾸어 저장할 만큼 좋은 확장자입니다.

2024-10-13 02:51 UTC, minsekim1 commented
절대 경로 사용도 적합했고 로딩 등 글로벌 컴포넌트 활용과  스토리보드 활용, 타입스크립트 활용 부분에서 인상 깊었습니다.

벌써부터 코드 스타일이 잘 확립되어 있다는 생각이 드는 소스코드들이였습니다.

코드 리뷰하는 중에도 깔끔하게 여러번 되돌아 볼 필요 없도록 잘 설계된 컴포넌트들이네요.

수고하셨습니다.

2024-10-19 05:52 UTC, eunjin210 commented on src/api/instance/index.ts
> +const jwtToken = localStorage.getItem('jwt_token');
처음 소셜로그인을 구현하다보니 토큰에 대한 깊은 이해가 없었던 것 같네요 확인하고 반영했습니다 감사합니다!

2024-10-19 06:14 UTC, eunjin210 commented on src/components/common/Sidebar/index.tsx
> +  function Sidebar({ isOpen, setIsOpen }: { isOpen: boolean; setIsOpen: any }) {
any말고 타입스크립트 답게 set 함수를 관리하는게 좋은 것 같아요 좋은 리뷰 감사드립니다.
타입을 새로 정의하여 반영하였습니다.
리뷰에 대한 답변과 반영이 늦어 죄송합니다 ㅜ 앞으로 더 빠른 답변드리도록 노력하겠습니다!
항상 감사드립니다 ㅎㅎ

2024-10-20 00:31 UTC, minsekim1 approved these changes

2024-10-20 00:36 UTC, minsekim1 approved these changes

2024-10-20 00:36 UTC, merged